version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # Bind the current directory to the container
      - /usr/src/app/node_modules # Avoid overriding node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true # Required for hot-reload to work inside Docker
